# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'variationalbayes'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About Me', path: 'menu', url: 'https://dibyaghosh.com'}
- {name: 'Archive', path: 'menu', url: 'writing.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/dibyaghosh'}
- {icon: 'twitter', link: 'https://twitter.com/its_dibya'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/dibyaghosh/'}
- {icon: 'rss-square', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related articles:'

post_date_prefix: 'Written on'
